//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class conductor
    {
        public conductor()
        {
            this.monitoreo = new HashSet<monitoreo>();
        }
    
        public int id_conductor { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string licencia { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<monitoreo> monitoreo { get; set; }
    }
}
