//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        public int id_incidencia { get; set; }
        public Nullable<int> id_monitoreo { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual monitoreo monitoreo { get; set; }
    }
}
