//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seguimiento_carga_anchaEntities : DbContext
    {
        public seguimiento_carga_anchaEntities()
            : base("name=seguimiento_carga_anchaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<conductor> conductor { get; set; }
        public DbSet<consumo_combustible> consumo_combustible { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<incidencia> incidencia { get; set; }
        public DbSet<mantenimiento> mantenimiento { get; set; }
        public DbSet<monitoreo> monitoreo { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<repuesto> repuesto { get; set; }
        public DbSet<ruta> ruta { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<vehiculo> vehiculo { get; set; }
    }
}
