//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitoreo
    {
        public monitoreo()
        {
            this.consumo_combustible = new HashSet<consumo_combustible>();
            this.incidencia = new HashSet<incidencia>();
        }
    
        public int id_monitoreo { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_conductor { get; set; }
        public Nullable<int> id_ruta { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<System.DateTime> fecha_llegada { get; set; }
        public string estado { get; set; }
    
        public virtual conductor conductor { get; set; }
        public virtual ICollection<consumo_combustible> consumo_combustible { get; set; }
        public virtual ICollection<incidencia> incidencia { get; set; }
        public virtual ruta ruta { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
