//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta
    {
        public ruta()
        {
            this.monitoreo = new HashSet<monitoreo>();
        }
    
        public int id_ruta { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public Nullable<decimal> distancia_km { get; set; }
    
        public virtual ICollection<monitoreo> monitoreo { get; set; }
    }
}
