//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public vehiculo()
        {
            this.mantenimiento = new HashSet<mantenimiento>();
            this.monitoreo = new HashSet<monitoreo>();
        }
    
        public int id_vehiculo { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string placa { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<decimal> capacidad_toneladas { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ICollection<mantenimiento> mantenimiento { get; set; }
        public virtual ICollection<monitoreo> monitoreo { get; set; }
    }
}
